version: '3.8'

services:
  # Django Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keynest-api
    expose:
      - "8000"
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - CACHE_LOCATION=${CACHE_LOCATION:-redis://redis:6379/1}
      - ALLOWED_HOSTS=envnest.shop,www.envnest.shop
      - SITE_URL=https://envnest.shop
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-KeyNest.settings}
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - redis
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      # Main API Router
      - "traefik.http.routers.api.rule=Host(`envnest.shop`) || Host(`www.envnest.shop`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=8000"

      # Redirect www → non-www
      - "traefik.http.routers.redirect.rule=Host(`www.envnest.shop`)"
      - "traefik.http.routers.redirect.entrypoints=web,websecure"
      - "traefik.http.routers.redirect.middlewares=redirect-to-main"
      - "traefik.http.middlewares.redirect-to-main.redirectregex.regex=^https?://www.envnest.shop/(.*)"
      - "traefik.http.middlewares.redirect-to-main.redirectregex.replacement=https://envnest.shop/$${1}"
      - "traefik.http.middlewares.redirect-to-main.redirectregex.permanent=true"

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: keynest-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Traefik Reverse Proxy + Let's Encrypt SSL
  traefik:
    image: traefik:v3.1
    container_name: keynest-traefik
    command:
      - "--api.insecure=true"                          # dashboard (disable in prod)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Force Let's Encrypt HTTP-01 challenge
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

      # Email for cert registration
      - "--certificatesresolvers.letsencrypt.acme.email=gychitresh1290@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"   # Traefik dashboard (http://your-ec2-ip:8080)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    restart: unless-stopped

  # Log Viewer
  dozzle:
    image: amir20/dozzle:latest
    container_name: keynest-dozzle
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - api
      - redis
      - traefik

volumes:
  redis_data:
  letsencrypt:

networks:
  default:
    name: keynest-network