name: Bug Report
description: File a bug report to help us improve KeyNest
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Try the latest version to see if the issue is fixed
        - Check our documentation for expected behavior

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: What happened instead?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Paste screenshots here...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Frontend (Next.js)
        - Backend (Django API)
        - Authentication
        - Database
        - Docker
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: KeyNest Version
      description: What version of KeyNest are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running KeyNest?
      options:
        - Development (local)
        - Docker (local)
        - Production (cloud)
        - Production (self-hosted)
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., macOS 14.0, Ubuntu 22.04, Windows 11

  - type: input
    id: browser
    attributes:
      label: Browser
      description: If this is a frontend issue, what browser are you using?
      placeholder: e.g., Chrome 120, Firefox 121, Safari 17

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output here.
      render: shell
      placeholder: Paste logs here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any other details that might help...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I've searched existing issues for duplicates
          required: true
        - label: I've tried the latest version
          required: true
        - label: I've checked the documentation
          required: true
        - label: I've provided all the required information
          required: true