name: Feature Request
description: Suggest a new feature or enhancement for KeyNest
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 💡
        
        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Check our roadmap to see if it's already planned
        - Consider if this fits with KeyNest's core mission

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Frontend (UI/UX)
        - Backend (API)
        - Authentication
        - Security
        - Performance
        - Documentation
        - DevOps/Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my usage
    validations:
      required: true

  - type: dropdown
    id: users
    attributes:
      label: User Impact
      description: Who would benefit from this feature?
      options:
        - Individual developers
        - Small teams (2-10)
        - Medium teams (11-50)
        - Large teams (50+)
        - Enterprise users
        - Open source projects
        - All users
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used.
      placeholder: |
        1. As a developer, I want to...
        2. When working on a team, I need to...
        3. For production deployments, it would help to...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, wireframes, or examples from other tools.
      placeholder: Paste images or links here...

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Users can...
        - [ ] The system should...
        - [ ] Documentation includes...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Any other details that might help...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I'm interested in implementing this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature
        - label: I can provide feedback during development

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I've searched existing issues for duplicates
          required: true
        - label: I've checked the project roadmap
          required: true
        - label: This feature aligns with KeyNest's mission
          required: true
        - label: I've provided clear use cases and examples
          required: true