# Generated by Django 4.2.23 on 2025-08-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(help_text='Environment name (e.g., dev, staging, prod)', max_length=100),
        ),
        migrations.AlterField(
            model_name='envvariable',
            name='key',
            field=models.CharField(help_text='Environment variable key name', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Organization display name', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Project identifier within organization', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Used as the primary login identifier', max_length=254, unique=True),
        ),
    ]
