# Generated by Django 4.2.23 on 2025-09-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organizationinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('import', 'Import'), ('activate', 'Activate'), ('password_reset_request', 'Password Reset Request'), ('password_reset_confirm', 'Password Reset Confirm'), ('login', 'Login'), ('logout', 'Logout')], max_length=30),
        ),
    ]
